name: EC2 Streamlit Deploy Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.secretkey }}" > key.pem
          chmod 400 key.pem

      - name: Copy Project Files
        run: |
          scp -o StrictHostKeyChecking=no -i key.pem -r app/ ec2-user@35.154.18.177:/home/ec2-user/
          scp -o StrictHostKeyChecking=no -i key.pem requirements.txt ec2-user@35.154.18.177:/home/ec2-user/

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@35.154.18.177 "
          
          echo '🚀 Starting Deployment...'

          cd /home/ec2-user

          # 🔥 Kill existing Streamlit app (if running)
          pkill -f streamlit || true

          # 🔹 Create virtual environment (only if not exists)
          if [ ! -d 'venv' ]; then
            python3 -m venv venv
          fi

          source venv/bin/activate

          pip install --upgrade pip
          pip install -r requirements.txt

          nohup streamlit run app/app.py \
            --server.port 8501 \
            --server.address 0.0.0.0 \
            > streamlit.log 2>&1 &

          echo '✅ Deployment Completed!'
          "
